### ISSUE TITLE
Document a pattern for seeAlso profiles

### ISSUE THREAD

**Issue by jpstroop** [IIIF/api#841] opened 2016-05-13 15:18 UTC
Media types don't exist or aren't granular enough. `seeAlso` is really just a refined `service` so document at http://iiif.io/api/annex/services/ one example of how to use the namespace (or XSD?) as the profile, e.g.:

``` json
seeAlso: {
  "@id": "http://wellcomelibrary.org/service/alto/b19956435/0?image=0",
  "format": "text/xml",
  "profile": "http://www.loc.gov/standards/alto/v3/alto.xsd",
  "label": "METS-ALTO XML"
}
```

**Comment by azaroth42** [comment] 2016-05-13 15:21
:-1: on putting it in services, but :+1: to documenting how to decide and record profile URI choice.

**Comment by mikeapp** [comment] 2016-05-13 15:36
👍 to the profile in `seeAlso`

**Comment by jpstroop** [comment] 2016-05-16 15:24
@azaroth42 where instead? Another note?

**Comment by azaroth42** [comment] 2016-05-16 17:29
I would prefer another note, parallel to the services one.  Otherwise it will be confusing as to which of service and seeAlso to use.  We should also maybe clarify the distinction as to when one would use one or the other, as I agree that there's overlap.

**Comment by zimeon** [comment] 2016-05-18 21:14
Hmmm... this seems a bit like "6 of one, and half a dozen of the other". In separate docs one see one and not the other, if combined then they get confused... Might be worth trying to write it separately but then revisiting the question before we decide.

**Comment by glenrobson** [comment] 2017-03-22 15:42
In the Newspaper group we've been discussing linking to ALTO, hOCR and Text and have proposed the profiles mentioned in the following doc (linking to text section): http://bit.ly/2a63PR6

**Comment by azaroth42** [comment] 2018-01-05 16:54
This is now a duplicate of the broader #1310. Closing.

**Closed by azaroth42** 2018-01-05 16:54 UTC
Labels: discovery, notes
