### ISSUE TITLE
Start property in collection context 

### ISSUE THREAD

**Issue by altomator** [IIIF/api#2233] opened 2023-05-12 16:55 UTC
I posted this request on the Mirador project first, but it seems to be relevant to the Presentation API specification:
https://github.com/ProjectMirador/mirador/issues/3475

As an editor of IIIF collections, one would like to reuse the existing IIIF manifests but add some modifications to some of them, for example the opening page of a specific document. But the `start` property doesn't work when used in a collection context to open a manifest at a specific canvas.

**Samples**

Collection: https://raw.githubusercontent.com/altomator/IIIF/main/collection/collection-bd.json
Sub-collection using the `start` property: https://raw.githubusercontent.com/altomator/IIIF/main/collection/collection-nemo.json

**Comment by azaroth42** [comment] 2024-06-07 00:58
Duplicate of #1991. The specification allows this (as discussed) the issue is for Mirador and other viewers to implement it.

Propose close.

**Comment by azaroth42** [comment] 2024-06-07 21:04
Editors agree invalid. Closing.

**Closed by azaroth42** 2024-06-07 21:04 UTC
Labels: presentation, invalid
