### ISSUE TITLE
Suggest an update in language used in AnnotationPage

### ISSUE THREAD

**Issue by mejackreed** [IIIF/api#1910] opened 2019-12-10 00:17 UTC
In our Mirador 3 implementation of `AnnotationPage` we ran into some language which was a little confusing on first read.

Specifically these sentences made it difficult to determine the difference between embedded and referenced `AnnotationPages`.

> Each Annotation Page can be embedded in its entirety, if the Annotations should be processed as soon as possible when the user navigates to that Canvas, or a reference to an external page. This reference must include id and type, must not include items and may include other properties, such as behavior.

Could we suggest splitting up this to individually discuss a referenced resource and an embedded one?

**Comment by azaroth42** [comment] 2019-12-10 16:57
Is the issue specifically about embedded and referenced, if so I think #1912 is the solution.
If the issue is about the sentence having both, then we can fix this one instance by splitting it up, but I'm not sure that's the root cause.

**Comment by mejackreed** [comment] 2019-12-10 17:21
I think it could be cleared up with #1912 as a solution. There was some ambiguity in understanding that `embedded` and `referenced` were specific classes/types of special things. The linked references will likely solve that. @jkeck @camillevilla what do you think?

**Comment by jkeck** [comment] 2019-12-10 18:09
Some sort of context (e.g. link or tooltip) on the instances `reference` in that piece of documentation would have reduced some confusion.

**Comment by azaroth42** [comment] 2020-01-08 17:19
Closing in favor of #1912. Thanks @mejackreed @jkeck!

**Closed by azaroth42** 2020-01-08 17:19 UTC
Labels: editorial, presentation
