### ISSUE TITLE
Differentiating between painting motivations

### ISSUE THREAD

**Issue by tomcrane** [IIIF/api#511] opened 2015-07-21 12:08 UTC
Given the param list in #508, how does a client differentiate between a search for OCRed or transcribed content (words that are actually in the image), and other annotations with the motivation "painting"?

**Comment by azaroth42** [comment] 2015-07-21 16:52
Are there use cases for searching with word based terms for content that is painting, but isn't words in the image?  I'm having trouble thinking of one.

To search for annotations that paint a resource, say a video, you would put the URI of the video into the `uri` param I think, in the same way as searching for a semantic tag URI

**Comment by tomcrane** [comment] 2015-07-22 10:29
What motivation would you use for *translations* where the text of the translation is supplied as annotations that identify rectangles (maybe each line is a separate anno, or each paragraph)?

"All resources which are to be displayed as part of the representation are given the motivation of 'sc:painting'" - a translation can be displayed as part of the representation (overlaid) but it's not the actual text in the image. 

In a search-within service powered by OCR of the printed text, I only want results that can paint a highlight showing the term I just searched for (with leeway for lemmatization and suchlike), not from any other text resources. If I supply "painting" as the motivation then I exclude commentary, but do I exclude everything else that could come under the "painting" motivation?

**Comment by azaroth42** [comment] 2015-07-29 16:19
Dependent somewhat on Prezi 2.1 (or subsequent) having a distinction between transcription painting and painting that associates other content with the canvas that isn't actually present in the object (e.g. translation of the content, or OCR corrections)

Eds not sure how to best support the use case :crying_cat_face:

**Comment by azaroth42** [comment] 2017-07-11 18:12
Given that motivations can be multiple and any URI, this seems like we should encourage experimentation before 3.0 as an effort to see if there's any actual functionality.  Otherwise, I suggest we close wontfix as out of scope for IIIF to be getting into the business of text taxonomies.

**Comment by azaroth42** [comment] 2017-08-30 16:22
Discussion on 08/30:  Need actual use cases and requirements that would affect the behavior of clients. Agreed that this isn't a presentation API issue (unless there really _are_ presentation requirements) and Discovery agreed it wasn't in scope for them.  Added defer, removed milestone, removed presentation tag.

**Comment by sdellis** [comment] 2017-08-30 18:40
The problem I see with using labels to distinguish transcription Layers from other types of Layers is that it's ultimately not interoperable. For example, let's say there is a Manifest that contains Canvases aggregated from various institutions (i.e., correspondence from multiple archives). You are likely to have transcriptions that are in multiple annotation stores, each of which labels the transcription Layer differently (i.e., "full-text" vs "transcriptions").  

If I want to encourage people to transcribe canvases that do not yet have a transcription, how would a machine flag all the pages that have been transcribed already, so that a user can select one to transcribe? Even when dealing with a single annotation store, you have to let the viewer know what the label is for it to present a usable interface. That could be a viewer config variable, but that's not ideal.

**Comment by benwbrum** [comment] 2017-09-04 14:47
As an aside to @sdellis, we are creating a transcription status service for FromThePage to communicate statuses of manifests and canvases.  This will be a `service`, rather than an annotation, communicating whether a page has been marked `blank`, `needs review`, contains transcribed content, contains corrected OCR text, contains translated content, or has been indexed.  

Something similar may be a way to solve that use case without relying on annotations.  An alternative might be to create a separate status annotation to be applied to a canvas, rather than relying on fields like `motivation` within the canvas.  We still run into the interoperability problem, though, when two authoring tools use different status annotations.

**Comment by sdellis** [comment] 2017-09-05 14:34
@benwbrum, thanks for the heads-up. It's an interesting approach for accommodating a common pattern in transcription interfaces, and it's a different use case than the interoperability issue that I brought up. 

Your suggestion to have a "status annotation" could work, but should probably have the "transcription annotation" as its target, rather than the canvas, to avoid confusion about which annotation the status refers to. And of course, targeting the annotation is dependent on how issue [#1019](https://github.com/IIIF/iiif.io/issues/1019) gets resolved.

I wish it were a simpler solution, but it sounds like it could be a possible workaround given the current lack of a Presentation API solution. Would your service require a request for every single page, or can the client make a single request that will return the transcription status of each transcription annotation (or lack thereof) in the manifest? 

At any rate, it looks like we have at least two more use cases here proving there are Presentation requirements affecting the behavior of clients. That's three in total, if we include the "search within" scenario presented earlier in this issue by @tomcrane.

**Comment by tomcrane** [comment] 2017-09-29 18:54
Ed's discussion (and see @jeffreycwitt - https://github.com/IIIF/api/issues/1258)

There are two related parts to this:

* One is more community recognised motivations for annotations - captioning, transcribing etc.
* The other is is summarising the contents of layers (or AnnotationCollections in P3) so that a client can group them together, or tie them to different parts of the user interface.

For example - all the annos in this collection are transcriptions, all the annotations in this collection are french subtitles for the film. A video player can make the captions available via a recognisable button, and the commentary in a more hidden part of the UI (@jronallo's use case).

For a _Presentation_ API, there may be no difference in how many of these are rendered. So how can it differentiate without crossing over into semantics? But... many people need this.

**Comment by azaroth42** [comment] 2018-01-05 16:46
This is now a duplicate of the new issues, esp #1258. Closing.

**Closed by azaroth42** 2018-01-05 16:46 UTC
Labels: defer, normative, search
