### ISSUE TITLE
JSON-LD and content negotation

### ISSUE THREAD

**Issue by thewilkybarkid** [IIIF/api#1685] opened 2018-10-09 08:20 UTC
Currently trying to implement the Image API v2 (and will tackle v3 later). I'm getting a bit confused by the wording of the `Content-Type` for image info requests (refs https://github.com/elifesciences/fastly-iiif/pull/3). 

In 2.0.0/2.1.1 it's:

> If the client explicitly wants the JSON-LD content-type, then it *must* specify this in an Accept header, otherwise the server *must* return the regular JSON content-type.

This reads to me as if `application/ld+json` _has_ to be present in an `Accept` header, eg `Accept: */*` (which is the same as no `Accept` header) isn't enough. (So the same as the [recommendation for WebP content negotiation](https://developers.google.com/speed/webp/faq#how_can_i_detect_browser_support_for_webp), support has to be explicitly advertised.)

(I note it doesn't mention the potential of `application/ld+json` having a [quality value of 0, which means 'not acceptable'](https://tools.ietf.org/html/rfc7231#section-5.3.1).)

But it seems like (at least some) existing implementations _do_ return `application/ld+json` in this case (see https://github.com/elifesciences/fastly-iiif/pull/3#discussion_r223418490)

The wording in 3.0.0-alpha is:

>  If the server receives a request with one of the content types above in the Accept header, it *should* respond with that content type following the rules of content negotiation. Otherwise, it *must* respond with the `application/json` content type.

Which now mentions content negotiation, but still seems to mean that `application/ld+json` has to be present in an `Accept` header.

https://github.com/IIIF/api/pull/1652 has been added to try and promote `application/ld+json`, but doesn't seem to make much difference: `application/ld+json` still has to be present in an `Accept` header.

(I don't use the other APIs, but they seem to have similar wording.)

To help clarify what should be happening, what is the expected `Content-Type` for the the following `Accept` header values in both image API v2 and v3 image requests when the `jsonldMediaType` feature is available?

1. No header
1. `*/*`
1. `application/*`
1. `application/ld+json`, `*/*`
1. `application/json, */*`
1. `*/*; q=1, application/ld+json; q=0.1`
1. `*/*; q=1, application/ld+json; q=0`

**Comment by azaroth42** [comment] 2018-10-09 16:00
The intent in 2.x is that the server will return `application/json` unless the client has a header that prefers `application/ld+json` explicitly.  The wording was intended to mean 'specifies it with more priority than any other media type' ... without going into the details of q values :)

For 3.0 technologies have caught up a little more, and we've changed the requirements. See: https://preview.iiif.io/api/image-prezi-rc2/api/image/3.0/#51-image-information-request

>The HTTP `Content-Type` header of the response SHOULD have the value `application/ld+json` with the `profile` parameter given as the context document: `http://iiif.io/api/image/3/context.json`

And then if that can't be generated, then fall back to `application/json`. So conneg isn't required to get the JSON-LD media type any more.

In 3.0 the answers to your 7 options:

1.  application/ld+json
2. application/ld+json
3. application/ld+json
4. application/ld+json
5. application/ld+json  (via the */*)
6. ditto
7. ditto

A server that supports conneg would return `application/json` only if the header was `Accept:  application/json` or otherwise that media type was a higher priority due to q values.

Hope that helps!

**Comment by thewilkybarkid** [comment] 2018-10-10 08:00
Thanks @azaroth42; what would you expect for 2.0/2.1? (Wording looks the same on both.)

**Comment by azaroth42** [comment] 2018-10-10 17:46
Then we should clarify the wording in 3.0 :)

2.x the intent is to allow the implementation to choose which, but to default to `application/json`. Thus the line that says if ld+json is desired, then the client MUST put it in the accept header.

So in 2.x, the answers to the 7 would be:

1. application/json
2. application/json
3. application/json
4. application/ld+json  (as it was requested explicitly, even if /json is at the same q value)
5. application/json
6. application/json - as the q values re given and /json is higher via the * / *
7. ditto

**Comment by thewilkybarkid** [comment] 2018-10-12 07:56
In terms of the v3 cases: for 6 it can be `application/json+ld` if the client's preference for `application/json` is ignored (which is fine), for 7 it should be `application/json` (the client's stating that anything other than `application/json+ld` is acceptable). More specific media types/ranges take precedence.

In terms of v2, my understanding is that content negotiation is not followed and the presence of a type in an `Accept` header is enough for it to be served (so 6 and 7 would be `application/ld+json`, even though I wouldn't expect them, especially the later).

> Then we should clarify the wording in 3.0 :)

Sorry, meant between 2.0 and 2.1!

That said, I think there should be some wording tweaks.

v3 currently has:

> If the server receives a request with one of the content types above in the Accept header, it _should_ respond with that content type following the rules of content negotiation. Otherwise, it _must_ respond with the `application/json` content type.

It should just say follow content negotiation (mentioning the types appearing in the header means it's the same as v2), with a preference of `application/json+ld` but fallback of `application/json`.

v2 could do with a clarification to say that content negotiation must not be followed (which is odd, but is what it seems to be trying to say).

**Comment by zimeon** [comment] 2018-11-12 16:07
Agreement in ed's discussion that the sentence "Otherwise, it MUST respond with the application/json content type." after discussion of content negotiation is confusing. Also suggest putting content negotiation comment before alternatives without.

**Comment by azaroth42** [comment] 2018-11-12 17:31
Closed by #1714

**Closed by azaroth42** 2018-11-12 17:31 UTC
Labels: discuss, editorial, image, presentation
